name: GaussBlur and rotation

on:
  push:
    branch:
        - main
        - master
  pull_request:
    branch:
        - main
        - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: | 
            sudo apt-get update
            sudo apt-get install -y build-essential
            sudo apt install libgtest-dev

      - name: Build project
        run: make all

      - name: Run tests
        run: make test ARGS="example.bmp 7 15.0"
